<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://hyundaidealer.com/AdminRevokeService/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  targetNamespace="http://hyundaidealer.com/AdminRevokeService/"
                  name="adminrevoke">
    <wsdl:types>
        <xs:schema targetNamespace="http://hyundaidealer.com/AdminRevokeService/">
            <xs:include schemaLocation="../xsd/adminrevoke.xsd"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="AdminRevokeRequest"><wsdl:part name="parameters" element="tns:AdminRevoke"/></wsdl:message>
    <wsdl:message name="AdminRevokeResponse"><wsdl:part name="parameters" element="tns:AdminRevokeResponse"/></wsdl:message>
    <wsdl:portType name="AdminRevokeService">
        <wsdl:operation name="AdminRevoke">
            <wsdl:input  message="tns:AdminRevokeRequest"/>
            <wsdl:output message="tns:AdminRevokeResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="AdminRevokeServiceSoapBinding" type="tns:AdminRevokeService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="AdminRevoke">
            <soap:operation soapAction=""/>
            <wsdl:input><soap:body use="literal"/></wsdl:input>
            <wsdl:output><soap:body use="literal"/></wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="AdminRevokeService">
        <wsdl:port name="AdminRevokeServicePort" binding="tns:AdminRevokeServiceSoapBinding">
            <soap:address location="/ws"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
