// poc/apps/role-api/src/fixtures.js
// ENA — User Attribute Database (matches legacy IAMUserProfile)
const users = {
  'dealer.user1': {
    role: 'DEALER_MANAGER', brand: 'H', dealer_code: 'H-001',
    first_name: 'John', last_name: 'Smith', email: 'john.smith@dealer.com',
    corporate_code: 'H-001', corporate_name: 'Hyundai Metro',
    job_code: 'DM', job_title: 'Dealer Manager',
    department: 'Sales', position: 'Manager',
    region_code: 'CE', sales_district: 'NY1', service_district: 'NY1', parts_district: 'NY1',
    dealer_state_code: 'NY', dealer_type_code: 'FULL',
    zone: 'East', district: 'NY',
    access_level: 'DEAR', permission_groups: 'NHDD;NDCR;FDCS',
  },
  'dealer.user2': {
    role: 'DEALER_STAFF', brand: 'GMA', dealer_code: 'GMA-042',
    first_name: 'Jane', last_name: 'Doe', email: 'jane.doe@genesis.com',
    corporate_code: 'GMA-042', corporate_name: 'Genesis West',
    job_code: 'SP', job_title: 'Sales Person',
    department: 'Parts', position: 'Staff',
    region_code: 'WE', sales_district: 'CA2', service_district: 'CA2', parts_district: 'CA2',
    dealer_state_code: 'CA', dealer_type_code: 'FULL',
    zone: 'West', district: 'CA',
    access_level: 'DEAR', permission_groups: 'NHDD;FDCS',
  },
  'vendor.user1': {
    role: 'VENDOR', brand: 'H', dealer_code: null,
    first_name: 'Vendor', last_name: 'Rep', email: 'vendor@external.com',
    corporate_code: '00000', corporate_name: 'External Vendor',
    job_code: 'VND', job_title: 'Vendor Representative',
    department: 'External', position: 'Vendor Rep',
    region_code: '', sales_district: '', service_district: '', parts_district: '',
    dealer_state_code: '', dealer_type_code: '',
    zone: '', district: '',
    access_level: 'NATL', permission_groups: 'NHDD',
  },
  'corp.user1': {
    role: 'CORPORATE', brand: 'H', dealer_code: null,
    first_name: 'Corp', last_name: 'User', email: 'corp@hma.com',
    corporate_code: '00000', corporate_name: 'HMA Corporate',
    job_code: 'ANL', job_title: 'Analyst',
    department: 'IT', position: 'Analyst',
    region_code: '', sales_district: '', service_district: '', parts_district: '',
    dealer_state_code: '', dealer_type_code: '',
    zone: '', district: '',
    access_level: 'NATL', permission_groups: '',
  },
  'corp.user2': {
    role: 'CORPORATE_ADMIN', brand: 'H', dealer_code: null,
    first_name: 'Admin', last_name: 'User', email: 'admin@hma.com',
    corporate_code: '00000', corporate_name: 'HMA Corporate',
    job_code: 'ADM', job_title: 'Administrator',
    department: 'IT', position: 'Admin',
    region_code: '', sales_district: '', service_district: '', parts_district: '',
    dealer_state_code: '', dealer_type_code: '',
    zone: '', district: '',
    access_level: 'NATL', permission_groups: 'NHDD;NDCR;FDCS;FILM',
  },
  'test0901': {
    role: 'VENDOR', brand: 'H', dealer_code: null,
    first_name: 'test', last_name: '0901', email: 'test0901@hac.ca',
    corporate_code: '00000', corporate_name: 'HAC Test',
    job_code: 'TST', job_title: 'Test User',
    department: '', position: '',
    region_code: '', sales_district: '', service_district: '', parts_district: '',
    dealer_state_code: '', dealer_type_code: '',
    zone: '', district: '',
    access_level: 'NATL', permission_groups: 'NHDD',
  },
  'dealer.ca01': {
    role: 'DEALER_MANAGER', brand: 'H', dealer_code: 'ON-1234',
    first_name: 'John', last_name: 'Dealer', email: 'john.dealer@hyundai-toronto.ca',
    corporate_code: 'ON-1234', corporate_name: 'Hyundai Toronto',
    job_code: 'DM;SM', job_title: 'Dealer Manager;Sales Manager',
    department: 'Sales', position: 'Manager',
    region_code: 'ON', sales_district: 'GTA', service_district: 'GTA', parts_district: 'GTA',
    dealer_state_code: 'ON', dealer_type_code: 'FULL',
    zone: 'Ontario', district: 'GTA',
    access_level: 'DEAR', permission_groups: 'NHDD;NDCR;FDCS',
  },
  'corp.hq01': {
    role: 'CORPORATE_ADMIN', brand: 'H', dealer_code: null,
    first_name: 'Katie', last_name: 'Kim', email: 'katie.kim@hac.ca',
    corporate_code: '00000', corporate_name: 'Hyundai Auto Canada',
    job_code: 'DEV', job_title: 'Software Developer',
    department: 'IT', position: 'Developer',
    region_code: '', sales_district: '', service_district: '', parts_district: '',
    dealer_state_code: '', dealer_type_code: '',
    zone: '', district: '',
    access_level: 'NATL', permission_groups: 'NHDD;NDCR;FDCS;FILM',
  },
};

module.exports = { users };
