/**
 * Mock PID test users — attribute values match the real PID SAML trace
 * from PID-ILS-Test0901-S-SAML-tracer-export-2026-02-13.
 *
 * The test0901 user mirrors the exact payload captured in the Canada ADFS trace.
 * Additional users cover different dealer/role scenarios.
 */
module.exports = {
  // ─── Exact match to the SAML trace payload ─────────────────────────
  'test0901': {
    pid: 'test0901',
    password: 'any',
    attributes: {
      hmgpid: 'test0901@stg-partner.hmg-corp.io',
      pid: 'test0901',
      federationId: 'test0901',
      username: 'test0901',
      samAccountName: 'test0901',
      haccpid: 'test0901@HAC.CA',
      nameId: 'test0901@HAC.CA',
      upn: 'test0901@HAC.CA',
      firstName: 'test',
      lastName: '0901',
      email: '[email]',
      name: 'test0901',
      fullName: 'test0901',
      displayName: 'test0901',
      dealerCode: '',
      hacDealerCode: '',
      physicalDeliveryOffice: '',
      department: '',
      position: '',
      company: '',
      dealerRole: '',
      dealerRoleCode: '',
      hacRoleCode: '',
      hacTitle: 'test0901',
      title: 'test0901',
      zone: '',
      hacZone: '',
      zoneCode: '',
      co: '',
      district: '',
      userLevel: '',
      language: '',
      phone: '',
      hacEmail: '',
      url: '',
      roles: [
        'ADFS Perf Academy Users',
        'ADFS Dealer CMS Users',
        'ADFS HAEA Users',
      ],
      memberOf: [
        'CN=ADFS Perf Academy Users,OU=ADFSGroups,OU=HAC Groups,DC=HAC,DC=CA',
        'CN=ADFS Dealer CMS Users,OU=ADFSGroups,OU=HAC Groups,DC=HAC,DC=CA',
        'CN=ADFS HAEA Users,OU=ADFSGroups,OU=HAC Groups,DC=HAC,DC=CA',
      ],
    },
  },

  // ─── Dealer user with full attributes ──────────────────────────────
  'dealer.ca01': {
    pid: 'dealer.ca01',
    password: 'any',
    attributes: {
      hmgpid: 'dealer.ca01@stg-partner.hmg-corp.io',
      pid: 'dealer.ca01',
      federationId: 'dealer.ca01',
      username: 'dealer.ca01',
      samAccountName: 'dealer.ca01',
      haccpid: 'dealer.ca01@HAC.CA',
      nameId: 'dealer.ca01@HAC.CA',
      upn: 'dealer.ca01@HAC.CA',
      firstName: 'John',
      lastName: 'Dealer',
      email: '[email]',
      name: 'dealer.ca01',
      fullName: 'John Dealer',
      displayName: 'John Dealer',
      dealerCode: 'ON-1234',
      hacDealerCode: 'ON-1234',
      physicalDeliveryOffice: 'Toronto',
      department: 'Sales',
      position: 'Manager',
      company: 'Hyundai Toronto',
      dealerRole: 'Dealer Manager',
      dealerRoleCode: 'DM',
      hacRoleCode: 'DM',
      hacTitle: 'Dealer Manager',
      title: 'Dealer Manager',
      zone: 'Ontario',
      hacZone: 'ON',
      zoneCode: 'ON',
      co: 'CA',
      district: 'GTA',
      userLevel: '3',
      language: 'en',
      phone: '[phone_number]',
      hacEmail: '[email]',
      url: '',
      roles: [
        'ADFS HAEA Users',
        'ADFS Dealer CMS Users',
        'ADFS Parts Users',
      ],
      memberOf: [
        'CN=ADFS HAEA Users,OU=ADFSGroups,OU=HAC Groups,DC=HAC,DC=CA',
        'CN=ADFS Dealer CMS Users,OU=ADFSGroups,OU=HAC Groups,DC=HAC,DC=CA',
        'CN=ADFS Parts Users,OU=ADFSGroups,OU=HAC Groups,DC=HAC,DC=CA',
      ],
    },
  },

  // ─── Corporate HQ user ─────────────────────────────────────────────
  'corp.hq01': {
    pid: 'corp.hq01',
    password: 'any',
    attributes: {
      hmgpid: 'corp.hq01@stg-partner.hmg-corp.io',
      pid: 'corp.hq01',
      federationId: 'corp.hq01',
      username: 'corp.hq01',
      samAccountName: 'corp.hq01',
      haccpid: 'corp.hq01@HAC.CA',
      nameId: 'corp.hq01@HAC.CA',
      upn: 'corp.hq01@HAC.CA',
      firstName: 'Katie',
      lastName: 'Kim',
      email: '[email]',
      name: 'corp.hq01',
      fullName: 'Katie Kim',
      displayName: 'Katie Kim',
      dealerCode: '',
      hacDealerCode: '',
      physicalDeliveryOffice: 'Markham',
      department: 'IT',
      position: 'Developer',
      company: 'Hyundai Auto Canada',
      dealerRole: '',
      dealerRoleCode: '',
      hacRoleCode: 'CORP',
      hacTitle: 'Software Developer',
      title: 'Software Developer',
      zone: '',
      hacZone: '',
      zoneCode: '',
      co: 'CA',
      district: '',
      userLevel: '5',
      language: 'en',
      phone: '',
      hacEmail: '[email]',
      url: '',
      roles: [
        'ADFS HAEA Users',
        'ADFS Admin Users',
      ],
      memberOf: [
        'CN=ADFS HAEA Users,OU=ADFSGroups,OU=HAC Groups,DC=HAC,DC=CA',
        'CN=ADFS Admin Users,OU=ADFSGroups,OU=HAC Groups,DC=HAC,DC=CA',
      ],
    },
  },
};
